### ISSUE TITLE
Fix Twitter scrape

### ISSUE THREAD

**Issue by AndreiIgna** [LayeredStudio/page-meta#2]
Twitter info is not scraped anymore, after twitter.com site update

**Comment by PVGrad** [comment]
@AndreiIgna 
I've managed to parse twitter meta with this init:
```
$preview = new Layered\PageMeta\UrlPreview([
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
]);
$preview->loadUrl('https://twitter.com/ArcticMonkeys/status/1327247088485240832');
$info  = $preview->getAll();
```

so the difference is in custom HTTP_USER_AGENT

**Comment by AndreiIgna** [comment]
Thanks @PVGrad, that's a clever solution.

I will add this in the project description, so it's easy to spot

**Comment by AndreiIgna** [comment]
This info is added in Readme now [`UrlPreview::getAll()`](#getall-array) and mentioned you for the tip, hope that's okay.
